### ISSUE TITLE
Projekt 1: "Możliwość pobrania częściowych wyników"

### ISSUE THREAD

**Issue by LRajkowski** [pbiecek/ProgramowanieWizualizacja2017#23]
Dzień dobry. Mam pytanie odnośnie kryterium oceny projektu 1, a konkretnie: co należy rozumieć poprzez "możliwość pobrania częściowych wyników"? Zapewne najlepsza odpowiedź brzmi: "dokładnie to, co jest napisane", ale niestety mam problemy z interpretacją takiego sformułowania. :) Z góry dziękuję za odpowiedź.

**Comment by pbiecek** [comment]
Rozwiązanie idealne, miałoby uchwyty archivista, pozwalające na pobranie wykresów / tabel jako uchwyty archivista (np. tak jak tutaj: https://rawgit.com/pbiecek/Eseje/master/GrammarOfGraphics.html) (http://pbiecek.github.io/archivist/)

Ale archivista jeszcze nie omawialiśmy, 
więc rozwiązanie na 100% zawiera zapisane w dowolnym formacie agregaty poazywane dla kolejnych krajów. Np. jeżeli raport ma tabele z liczbą dzieci lubiących matematykę vs wyniki z matematyki, to te tabele są też zapisane jako pliki txt lub excel lub dowolne inne z których można sobie te tabele odczytać bez konieczności przeliczania ich na nowo.

**Comment by LRajkowski** [comment]
Rozumiem, dziękuję za odpowiedź (tym razem dziękuję z dołu :) ).
